site_name: Numérique et sciences informatiques
theme:
  name: material
  custom_dir: my_theme_customizations/
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for light mode
    - scheme: my_theme
      toggle:
        icon: material/weather-night
        name: Passer en mode nuit
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Passer en mode jour
  font:
    text: Roboto
    code: Roboto Mono

site_url: https://nsi.erwandemerville.fr/
copyright: Copyright &copy; 2023 - Erwan Demerville
nav:
  - Accueil:
    - index.md
  - Première:
    - premiere/index.md
    - Les bases de Python:
      - premiere/bases_python/index.md
      - Introduction au Python: premiere/bases_python/cours.md
      - Découverte de l'IDE Thonny: premiere/bases_python/thonny.md
      - Jeu - Chasse au trésor: premiere/bases_python/chassetresor.md
      - Exercices sur les fonctions: premiere/bases_python/exercices_fonctions.md
      - Notebooks: premiere/bases_python/notebooks.md
    - Représentation des données:
      - premiere/representation_donnees/index.md
      - Cours: premiere/representation_donnees/cours.md
      - Exercices et notebooks : premiere/representation_donnees/exercices.md
  - Terminale:
    - terminale/index.md
    - Modularité:
      - terminale/modularite/index.md
      - Activité - Utilisation d'une API: terminale/modularite/api.md
      - Gestion de modules: terminale/modularite/modules.md
    - Mise au point de programmes:
      - terminale/mise_au_point/index.md
      - Activité préliminaire: terminale/mise_au_point/preliminaire.md
      - Cours et exercices: terminale/mise_au_point/cours.md
      - Activité finale: terminale/mise_au_point/activite_finale.md
      - Corrigé DS n°1: terminale/mise_au_point/ds1.md
    - Programmation orientée objet:
      - terminale/poo/index.md
      - Activité d'introduction: terminale/poo/preliminaire.md
      - Cours: terminale/poo/cours.md
      - TP - Un jeu Pokémon: terminale/poo/pokemon.md
      - Exercices: terminale/poo/exercices.md
    - Récursivité:
      - terminale/recursivite/index.md
      - Introduction: terminale/recursivite/introduction.md
      - Cours: terminale/recursivite/cours.md
      - Exercices: terminale/recursivite/exercices.md
    - Sujet e3c:
      - terminale/e3c/index.md
    - Entraînement Python:
      - terminale/entrainement_python/index.md
  - Rendu des travaux: rendus.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      title: Sur cette page
      permalink: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html

plugins:
    - search
    - macros
    - mkdocs-video
    - open-in-new-tab

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

