site_name: Numérique et sciences informatiques
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for light mode
    - scheme: my_theme
      toggle:
        icon: material/weather-night
        name: Passer en mode nuit
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Passer en mode jour
  font:
    text: Roboto
    code: Roboto Mono

site_url: https://nsi.erwandemerville.fr/
copyright: Copyright &copy; 2023 - Erwan Demerville
nav:
  - Accueil:
    - index.md
  - Première:
    - premiere/index.md
    - Découverte de Thonny:
      - premiere/thonny/index.md
    - Les bases de Python:
      - premiere/bases_python/index.md
    - Tris:
      - premiere/tris/index.md
      - Tri par sélection: premiere/tris/tri_selection.md
      - Tri par insertion: premiere/tris/tri_insertion.md
  - Terminale:
    - terminale/index.md
    - Modularité:
      - terminale/modularite/index.md
      - Activité - Utilisation d'une API: terminale/modularite/api.md
      - Gestion de modules: terminale/modularite/modules.md
    - Mise au point de programmes:
      - terminale/mise_au_point/index.md
      - Activité préliminaire: terminale/mise_au_point/preliminaire.md
    - Arbres:
      - terminale/arbres/index.md
      - Cours:
        - Définitions et vocabulaire: terminale/arbres/vocabulaire.md
        - Parcours d'arbres binaires: terminale/arbres/parcours.md
        - Type abstrait "Arbre binaire": terminale/arbres/type_abstrait.md
        - Arbres binaires de recherche: terminale/arbres/abr.md
      - Activités Python:
        - Implémentation d'un arbre binaire: terminale/arbres/implementation_arbres.md
        - Implémentation d'un arbre binaire de recherche: terminale/arbres/implementation_abr.md
      - Exercices:
        - Vocabulaire sur les arbres: terminale/arbres/exercices_vocabulaire.md
        - Parcours d'arbres binaires: terminale/arbres/exercices_parcours.md
        - Arbre binaires de recherche: terminale/arbres/exercices_abr.md
        - Implémentations d'arbres binaires et ABR: terminale/arbres/implementations_arbres.md
      - Évaluations:
        - Évaluation 1 corrigée: terminale/arbres/evaluation_correction.pdf
        - Évaluation 2: terminale/arbres/evaluation_v2.pdf

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      title: Sur cette page
      permalink: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css
  - premiere/tris/stylesheets/style_animation_tri_selection.css
  - premiere/tris/stylesheets/style_animation_tri_insertion.css

extra_javascript:
  - javascripts/mathjax.js
  - premiere/tris/javascripts/animation_tri_selection.js
  - premiere/tris/javascripts/animation_tri_insertion.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

