site_name: Numérique et sciences informatiques
theme:
  name: material
  custom_dir: my_theme_customizations/
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for light mode
    - scheme: my_theme
      toggle:
        icon: material/weather-night
        name: Passer en mode nuit
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Passer en mode jour
  font:
    text: Roboto
    code: Roboto Mono

site_url: https://nsi.erwandemerville.fr/
copyright: Copyright &copy; 2023 - Erwan Demerville
nav:
  - Accueil:
    - index.md
  - Première:
    - premiere/index.md
    - Les bases de Python:
      - premiere/bases_python/index.md
      - Introduction au Python: premiere/bases_python/cours.md
      - Correction DM 1: premiere/bases_python/dm1.md
      - Découverte de l'IDE Thonny: premiere/bases_python/thonny.md
      - Notebooks et exercices: premiere/bases_python/notebooks.md
    - Représentation des données:
      - premiere/representation_donnees/index.md
      - Cours: premiere/representation_donnees/cours.md
      - Exercices et notebooks : premiere/representation_donnees/exercices.md
    - Tris:
      - premiere/tris/index.md
      - Tri par sélection: premiere/tris/tri_selection.md
      - Tri par insertion: premiere/tris/tri_insertion.md
  - Terminale:
    - terminale/index.md
    - Modularité:
      - terminale/modularite/index.md
      - Activité - Utilisation d'une API: terminale/modularite/api.md
      - Gestion de modules: terminale/modularite/modules.md
    - Mise au point de programmes:
      - terminale/mise_au_point/index.md
      - Activité préliminaire: terminale/mise_au_point/preliminaire.md
      - Cours et exercices: terminale/mise_au_point/cours.md
      - Activité finale: terminale/mise_au_point/activite_finale.md
    - Programmation orientée objet:
      - terminale/poo/index.md
      - Activité d'introduction: terminale/poo/preliminaire.md
      - Cours: terminale/poo/cours.md
      - TP - Un jeu Pokémon: terminale/poo/pokemon.md
      - Exercices: terminale/poo/exercices.md
    - Récursivité:
      - terminale/recursivite/index.md
      - Cours: terminale/recursivite/cours.md
      - Exercices: terminale/recursivite/exercices.md
    - Listes chaînées:
      - terminale/listes/index.md
      - Cours: terminale/listes/cours.md
      - Exercices: terminale/listes/exercices.md
    - Arbres:
      - terminale/arbres/index.md
      - Cours:
        - Définitions et vocabulaire: terminale/arbres/vocabulaire.md
        - Parcours d'arbres binaires: terminale/arbres/parcours.md
        - Type abstrait "Arbre binaire": terminale/arbres/type_abstrait.md
        - Arbres binaires de recherche: terminale/arbres/abr.md
      - Activités Python:
        - Implémentation d'un arbre binaire: terminale/arbres/implementation_arbres.md
        - Implémentation d'un arbre binaire de recherche: terminale/arbres/implementation_abr.md
      - Exercices:
        - Vocabulaire sur les arbres: terminale/arbres/exercices_vocabulaire.md
        - Parcours d'arbres binaires: terminale/arbres/exercices_parcours.md
        - Arbre binaires de recherche: terminale/arbres/exercices_abr.md
        - Implémentations d'arbres binaires et ABR: terminale/arbres/implementations_arbres.md
      - Évaluations:
        - Évaluation 1 corrigée: terminale/arbres/evaluation_correction.pdf
        - Évaluation 2: terminale/arbres/evaluation_v2.pdf
  - Pyxel: https://nuitducode.github.io/DOCUMENTATION/PYTHON/01-presentation/
  - Rendu des travaux: rendus.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      title: Sur cette page
      permalink: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
    - search
    - macros

extra_css:
  - stylesheets/extra.css
  - premiere/tris/stylesheets/style_animation_tri_selection.css
  - premiere/tris/stylesheets/style_animation_tri_insertion.css

extra_javascript:
  - javascripts/mathjax.js
  - premiere/tris/javascripts/animation_tri_selection.js
  - premiere/tris/javascripts/animation_tri_insertion.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

